In [1]:
import numpy as np 

### creating numpy array

In [2]:
arr1 = np.array([1, 6, 8, 9])
print(arr1)
print(type(arr1))

[1 6 8 9]
<class 'numpy.ndarray'>


## creating two dimension array

In [3]:
array_2d = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print(array_2d)
print(type(array_2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


### to check the dimension of array

In [4]:
array_2d.ndim

2

creating three dimension array

In [5]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[11, 12, 13], [77, 88, 99]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [77, 88, 99]]])

In [6]:
arr_100 = np.arange(1, 101)
arr_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### linespace function

In [7]:
arr2 = np.linspace(1, 10, 10)
print(arr2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
arr2 = np.linspace(1, 5, 10)
print(arr2)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### Creating zero, ones and identity matrix

In [9]:
arr_zero = np.zeros((8, 8), dtype=int)
arr_zero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
arr_ones = np.ones((9, 8), dtype=int)
arr_ones

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [11]:
arr_identity = np.eye(8)
arr_identity

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### to check the shape of nd array

In [12]:
array_3d.shape

(2, 2, 3)

In [13]:
l1 = [1, 5, 7]
l2 = [1, 8, 5]
l3 = l1 + l2
print(l3)

[1, 5, 7, 1, 8, 5]


In [14]:
arr1 = np.array([4, 5, 6])
arr2 = np.array([4, 7, 8])
print(arr1 + arr2)

[ 8 12 14]


In [15]:
arr1 = np.array([[4, 5, 6], [4, 5, 8]])
arr2 = np.array([[4, 7, 8], [4, 5, 8]])
print(arr1 * arr2)

[[16 35 48]
 [16 25 64]]


In [16]:
arr1 = np.array([[4, 5, 6], [4, 5, 8], [4, 8, 9]])
arr2 = np.array([[4, 7, 8], [4, 5, 8], [7, 8, 4]])
print(arr1 @ arr2)

[[ 78 101  96]
 [ 92 117 104]
 [111 140 132]]


In [17]:
list1 = np.array([1, 2, 3, 4])
list1 = list1 * 2
print(list1)

[2 4 6 8]


In [19]:
array1d = np.arange(1, 101)
array1d

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
array2d = array1d.reshape(5, 20)
array2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])