In [1]:
import numpy as np

In [8]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[2, 2, 2, 2]])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

[[1 2 3 4]
 [2 2 2 2]]


In [9]:
arr3 = np.concatenate((arr1, arr2), axis = 1)
arr3

array([[1, 2, 3, 4, 2, 2, 2, 2]])

In [10]:
arr4 = np.array([[4, 5, 6, 7], [9, 9, 9, 9]])
arr5 = np.array([[4, 5, 6, 7], [1, 1, 1, 1]])
arr6 = np.concatenate((arr4, arr5), axis=0)
arr6

array([[4, 5, 6, 7],
       [9, 9, 9, 9],
       [4, 5, 6, 7],
       [1, 1, 1, 1]])

In [11]:
arr7 = np.concatenate((arr4, arr5), axis=1)
arr7

array([[4, 5, 6, 7, 4, 5, 6, 7],
       [9, 9, 9, 9, 1, 1, 1, 1]])

In [13]:
arr8 = np.vstack((arr4, arr5))
arr8

array([[4, 5, 6, 7],
       [9, 9, 9, 9],
       [4, 5, 6, 7],
       [1, 1, 1, 1]])

In [14]:
arr9 = np.hstack((arr1, arr2))
arr9

array([[1, 2, 3, 4, 2, 2, 2, 2]])

In [ ]:
arr10 = np.array([[1, 2, 3], [4, 5, 6]])
arr11 = np.array([[1, 2, 3]])
# np.hstack((arr10, arr11)) ### NOT Possible
np.vstack((arr10, arr11))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
arr12 = np.array([[10], [10]])
np.hstack((arr10, arr12))

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10]])