In [1]:
import numpy as np

In [2]:
array1 = np.linspace(-np.pi, np.pi, 10)
array1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [3]:
Sin_value = np.sin(array1)
Sin_value

array([-1.22464680e-16, -6.42787610e-01, -9.84807753e-01, -8.66025404e-01,
       -3.42020143e-01,  3.42020143e-01,  8.66025404e-01,  9.84807753e-01,
        6.42787610e-01,  1.22464680e-16])

In [4]:
Sin_value = np.round(Sin_value, 3)
Sin_value

array([-0.   , -0.643, -0.985, -0.866, -0.342,  0.342,  0.866,  0.985,
        0.643,  0.   ])

### using mean in numpy array

In [5]:
array1 = np.array([1, 5, 7, 8])
mean = np.mean(array1)
print(mean)

5.25


In [6]:
array2 = np.array([[6, 7, 8, 10], [8, 3, 5, 12], [10, 23, 4, 6], [10, 12, 16, 18]])
array2

array([[ 6,  7,  8, 10],
       [ 8,  3,  5, 12],
       [10, 23,  4,  6],
       [10, 12, 16, 18]])

In [7]:
mean1 = np.mean(array2)
print(mean1)
# mean1

9.875


In [8]:
mean2 = np.mean(array2, axis=0)
print(mean2)

[ 8.5  11.25  8.25 11.5 ]


### Random number in numpy

In [9]:
rand_array1 = np.random.rand(4, 4)
rand_array1

array([[5.23561502e-01, 7.16289532e-01, 4.88673568e-02, 5.31080286e-01],
       [7.93724978e-01, 8.78756502e-01, 5.49043793e-01, 2.35521979e-01],
       [7.45021130e-01, 9.50034144e-02, 9.02066903e-01, 7.73043494e-01],
       [7.53389496e-04, 7.23757418e-01, 1.77011176e-01, 7.98820509e-01]])

In [10]:
randint_array = np.random.randint(10, 20, size=(4, 5))
randint_array

array([[12, 14, 18, 12, 19],
       [19, 12, 11, 10, 16],
       [14, 12, 11, 16, 17],
       [14, 17, 12, 15, 19]], dtype=int32)

In [11]:
rand_array1

array([[5.23561502e-01, 7.16289532e-01, 4.88673568e-02, 5.31080286e-01],
       [7.93724978e-01, 8.78756502e-01, 5.49043793e-01, 2.35521979e-01],
       [7.45021130e-01, 9.50034144e-02, 9.02066903e-01, 7.73043494e-01],
       [7.53389496e-04, 7.23757418e-01, 1.77011176e-01, 7.98820509e-01]])

### Split() method in numy array

In [13]:
randint_array = np.array_split(randint_array, 5)
randint_array

[array([[[12, 14, 18, 12, 19]]], dtype=int32),
 array([[[19, 12, 11, 10, 16]]], dtype=int32),
 array([[[14, 12, 11, 16, 17]]], dtype=int32),
 array([[[14, 17, 12, 15, 19]]], dtype=int32),
 array([], shape=(0, 1, 5), dtype=int32)]

In [14]:
array_1 = np.random.randint(10, 51, size=(5, 6))
array_1

array([[29, 27, 48, 18, 29, 47],
       [20, 49, 17, 37, 27, 22],
       [45, 13, 15, 49, 22, 27],
       [44, 26, 21, 45, 27, 32],
       [40, 30, 45, 24, 29, 30]], dtype=int32)

In [19]:
array_first, array_second = np.array_split(array_1, [3], axis=0)

In [18]:
array_first

array([[29, 27, 48, 18, 29, 47],
       [20, 49, 17, 37, 27, 22],
       [45, 13, 15, 49, 22, 27]], dtype=int32)

In [20]:
array_second

array([[44, 26, 21, 45, 27, 32],
       [40, 30, 45, 24, 29, 30]], dtype=int32)

In [ ]:
array_columnpart1, array_columnpart2, array_columnpart3 = np.array_split(array_1, [2, 4], axis=1)

In [28]:
array_columnpart1.shape
array_columnpart2.shape

(5, 3)

### loading the data from txt

In [45]:
iris_array = np.genfromtxt(r"F:\AI_ML_classes\numpy\iris.txt", delimiter=',', dtype=str)

In [46]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [47]:
features, labels = np.split(iris_array, [4], axis=1)

In [48]:
features.shape

(150, 4)

In [49]:
labels.shape

(150, 1)

In [50]:
features[:5]

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2']], dtype='<U15')

In [51]:
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [54]:
features = features.astype(float)

In [55]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [57]:
mean_features = np.mean(features, axis=0)
mean_features

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

In [58]:
arr = np.array([[2, 3, 4, 5],
                [6, 7, 8, 9],
                [10, 11, 12, 13]])

arr2 = np.array([[3, 3, 3, 4]])

In [59]:
arr + arr2

array([[ 5,  6,  7,  9],
       [ 9, 10, 11, 13],
       [13, 14, 15, 17]])