In [ ]:
import numpy as np

In [ ]:
print("hello world")

hello world


In [ ]:
array1 = np.array([1, 2, 3, 4], ndmin = 5)
print(array1)
print(array1.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


## Operation in array

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
print(array1[3])


4


In [ ]:
arr2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2d)

print(arr2d[1, 2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8


### Slicing in numpy array

In [ ]:
arr2d = np.array([[1, 2, 3,], [4, 5, 6],[7, 8, 9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### SYNTAX ↘
###         array2[start_row:end-row, start_column:end_column]

In [ ]:
arr2d = np.array([[1, 2, 3, 101], [4, 5, 6, 102],[7, 8, 9, 103], [10, 11, 12, 104]])
print(arr2d)

[[  1   2   3 101]
 [  4   5   6 102]
 [  7   8   9 103]
 [ 10  11  12 104]]


In [ ]:
arr2d = np.array([[1, 2, 3, 101], [4, 5, 6, 102],[7, 8, 9, 103], [10, 11, 12, 104]])
print(arr2d[1:3, 1:3])

[[5 6]
 [8 9]]


### Rearrange

In [ ]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr2d_1d = arr2d.reshape(12)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr2d_1d_reshape = arr2d_1d.reshape(6, 2)
print(arr2d_1d_reshape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [1]:
import numpy as np
import pandas as pd